# Generated by Django 4.1.7 on 2023-03-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_thumbnails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='thumbnails',
            new_name='thumbnail',
        ),
    ]
